import { Platform } from 'react-native';
import colors from './colors';

export default {
  text: {
    color: colors.black,
    // lineHeight: 11,
    size: 8,
    translateNumbers: false,
  },
  indicator: {
    size: 10,
    color: 'primary',
  },
  icon: {
    size: 7,
    color: colors.white,
    type: 'Ionicons',
  },
  button: {
    height: Platform.OS === 'android' ? 7 : 6,
    borderRadius: 10,
    size: 8,
    color: 'white',
    bold: true,
    backgroundColor: 'primary',
    disabledColor: '#f3f4f5',
    disabledBackgroundColor: 'disabled',
  },
  image: {
    resizeMode: 'cover',
    progressColor: 'primary',
    errorColor: 'black',
    errorBackgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  inputError: {
    color: 'error',
    sizeScale: 0.8,
  },
  input: {
    size: 7,
    activeColor: 'primary',
    inactiveColor: '#D0D0D0',
    color: colors.black,
    // backgroundColor: '#F5F5F5',
    placeholderColor: colors.black,
    center: false,
    translateNumbers: true,
    paddingHorizontal: 5,
    paddingVertical: 5,
    borderColor: colors.graytext,
    borderRadius: 10,
    borderWidth: 0.5,
    height: Platform.OS === 'android' ? 7 : 6,
    elevation: 1,
    returnKeyType: 'done',
  },
  formInputFrame: {
    size: 5,
    placeholderColor: '#858F96',
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderColor: 'inputBorderColor',
    borderWidth: 1,
    borderRadius: 4,
    height: 8,
  },
  textArea: {
    size: 7,
    color: colors.black,
    backgroundColor: colors.white,
    placeholderColor: colors.black,
    height: 20,
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderColor: colors.graytext,
    borderWidth: 0.5,
    borderRadius: 10,
    translateNumbers: false,
    underlineColor: 'transparent',
  },
  picker: {
    size: 7,
    color: colors.black,
    backgroundColor: colors.white,
    placeholderColor: colors.black,
    paddingVertical: 3,
    paddingHorizontal: 3,
    borderColor: colors.graytext,
    borderWidth: 0.5,
    borderRadius: 10,
    height: Platform.OS === 'android' ? 7 : 6,
  },
  wheelPicker: {
    size: 5,
    color: '#484848',
    backgroundColor: 'white',
    paddingVertical: 4,
    borderRadius: 4,
    height: 7.5,
    placeholderColor: '#858F96',
    borderColor: 'inputBorderColor',
    borderWidth: 1,
  },
  datePicker: {
    size: 7,
    color: colors.black,
    backgroundColor: colors.bg,
    placeholderColor: colors.black,
    paddingVertical: 4,
    borderColor: colors.graytext,
    borderWidth: 1,
    borderRadius: 10,
    height: Platform.OS === 'android' ? 7 : 6,
  },
  radioButton: {
    activeColor: 'primary',
    normalColor: 'grey',
    size: 5.5,
    labelColor: 'black',
    labelSize: 6.5,
  },
  checkBox: {
    activeColor: colors.primary,
    normalColor: colors.primary,
    size: 6,
    // elevation: 3,
    labelColor: colors.black,
    labelSize: 8,
    borderColor: colors.black,
    paddingLeft: 5,
  },
  toggleButtons: {
    activeBackgroundColor: 'primary',
    inActiveBackgroundColor: 'white',
    activeColor: 'white',
    inActiveColor: '#979797',
    activeBorderColor: 'primary',
    inActiveBorderColor: '#979797',
  },
  list: {
    indicatorColor: 'primary',
    errorLabelColor: 'error',
    noResultsLabelColor: 'black',
    retryButtonBackgroundColor: 'primary',
    retryButtoncolor: 'white',
  },
  tabBar: {
    height: 7,
    backgroundColor: colors.primary,
    activeTextColor: colors.white,
    activeTextSize: 7,
    activeTextBold: true,
    inactiveTextColor: '#B1B0B0',
    inactiveTextSize: 7,
    inactiveTextBold: false,
    underlineColor: colors.white,
    underlineHeight: 50,
  },
  tabBar2: {
    height: 10,
    backgroundColor: 'primary',
    activeTextColor: 'white',
    activeTextSize: 5,
    activeTextBold: true,
    inactiveTextColor: '#B1B0B0',
    inactiveTextSize: 5,
    inactiveTextBold: false,
    underlineColor: 'white',
    underlineHeight: 5,
  },
  swiper: {
    indicatorColor: '#ADAAAA',
    indicatorActiveColor: '#D6091D',
  },
  localNotifications: {
    info: {
      backgroundColor: '#333',
      closeColor: 'primary',
    },
    success: {
      backgroundColor: 'safe',
      closeColor: 'white',
    },
    error: {
      backgroundColor: 'error',
      closeColor: 'white',
    },
  },
};
